import { StyleSheet } from "react-native";
import { Palette } from "@/constants/Colors";

export const styles = StyleSheet.create({
	root: {
		flex: 1,
	},
	container: {
		flex: 1,
		backgroundColor: Palette.blue.dark,
	},
	scrollContent: {
		padding: 20,
		paddingTop: 52,
		paddingBottom: 48,
	},
	loadingContainer: {
		flex: 1,
		backgroundColor: Palette.blue.dark,
		alignItems: "center",
		justifyContent: "center",
	},
	header: {
		flexDirection: "row",
		alignItems: "center",
		marginBottom: 24,
	},
	avatarCircle: {
		width: 40,
		height: 40,
		borderRadius: 20,
		backgroundColor: Palette.green.mid,
		alignItems: "center",
		justifyContent: "center",
		marginLeft: 12,
	},
	avatarInitial: {
		fontSize: 18,
		fontWeight: "700",
		color: "#fff",
	},
	headerTitle: {
		color: "#fff",
		marginBottom: 4,
	},
	subtitle: {
		fontSize: 15,
		color: "rgba(255,255,255,0.55)",
		marginTop: 4,
	},
	section: {
		marginTop: 24,
	},
	sectionHeader: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		marginBottom: 16,
	},
	sectionTitleRow: {
		flexDirection: "row",
		alignItems: "center",
		gap: 7,
	},
	sectionTitle: {
		color: "#fff",
	},
	addButton: {
		flexDirection: "row",
		alignItems: "center",
		gap: 5,
		paddingVertical: 7,
		paddingHorizontal: 14,
		backgroundColor: Palette.green.mid,
		borderRadius: 20,
	},
	addButtonText: {
		fontSize: 14,
		color: "#fff",
		fontWeight: "600",
	},
	tripCard: {
		flexDirection: "row",
		borderRadius: 14,
		marginBottom: 12,
		backgroundColor: "rgba(255,255,255,0.07)",
		borderWidth: 1,
		borderColor: "rgba(255,255,255,0.12)",
		overflow: "hidden",
	},
	tripAccentBar: {
		width: 4,
	},
	tripCardContent: {
		flex: 1,
		padding: 14,
	},
	tripHeader: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "flex-start",
		marginBottom: 10,
	},
	tripTitle: {
		fontSize: 15,
		fontWeight: "600",
		color: "#fff",
		marginBottom: 3,
	},
	tripDate: {
		fontSize: 12,
		color: "rgba(255,255,255,0.5)",
	},
	tripCost: {
		fontSize: 17,
		fontWeight: "700",
		color: Palette.green.mid,
	},
	tripDetails: {
		flexDirection: "row",
		flexWrap: "wrap",
		gap: 10,
	},
	tripDetail: {
		flexDirection: "row",
		alignItems: "center",
		gap: 4,
	},
	tripDetailText: {
		fontSize: 12,
		color: "rgba(255,255,255,0.55)",
	},
	showAllButton: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		gap: 5,
		paddingVertical: 12,
		marginTop: 4,
	},
	showAllText: {
		fontSize: 13,
		color: Palette.blue.light,
		fontWeight: "500",
	},
	favoritesGrid: {
		flexDirection: "row",
		flexWrap: "wrap",
		gap: 10,
	},
	favoriteCard: {
		width: "48%",
		backgroundColor: "rgba(255,255,255,0.07)",
		borderRadius: 12,
		padding: 12,
		borderWidth: 1,
		borderColor: "rgba(255,255,255,0.12)",
		overflow: "hidden",
	},
	fillOverlay: {
		position: "absolute",
		bottom: 0,
		left: 0,
		right: 0,
		backgroundColor: "rgba(63,178,143,0.45)",
	},
	flashOverlay: {
		position: "absolute",
		top: 0,
		left: 0,
		right: 0,
		bottom: 0,
		backgroundColor: Palette.green.mid,
	},
	favoriteCardTop: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "flex-start",
		marginBottom: 8,
	},
	favoriteRoute: {
		flex: 1,
		fontSize: 13,
		fontWeight: "600",
		color: "#fff",
		marginRight: 6,
	},
	favoriteBadge: {
		backgroundColor: Palette.green.mid,
		borderRadius: 10,
		paddingHorizontal: 6,
		paddingVertical: 2,
	},
	favoriteBadgeText: {
		color: "#fff",
		fontSize: 11,
		fontWeight: "600",
	},
	favoriteCardBottom: {
		flexDirection: "row",
		alignItems: "center",
		gap: 4,
	},
	favoriteTransport: {
		fontSize: 12,
		color: Palette.blue.light,
		flex: 1,
	},
	favoriteDistance: {
		fontSize: 12,
		color: "rgba(255,255,255,0.5)",
	},
	emptyState: {
		alignItems: "center",
		paddingVertical: 36,
		gap: 8,
	},
	emptyStateTitle: {
		fontSize: 16,
		fontWeight: "600",
		color: "rgba(255,255,255,0.6)",
		marginTop: 8,
	},
	emptyStateSubtitle: {
		fontSize: 13,
		color: "rgba(255,255,255,0.35)",
		textAlign: "center",
		paddingHorizontal: 24,
	},
	emptyStateCTA: {
		flexDirection: "row",
		alignItems: "center",
		gap: 6,
		marginTop: 12,
		paddingVertical: 10,
		paddingHorizontal: 20,
		backgroundColor: Palette.green.mid,
		borderRadius: 20,
	},
	emptyStateCTAText: {
		fontSize: 14,
		color: "#fff",
		fontWeight: "600",
	},
	logoutSection: {
		marginTop: 36,
	},
	logoutButton: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		gap: 8,
		paddingVertical: 14,
		borderRadius: 12,
		borderWidth: 1.5,
		borderColor: Palette.red.light,
	},
	logoutButtonText: {
		color: Palette.red.light,
		fontSize: 15,
		fontWeight: "600",
	},
});
